### ISSUE TITLE
Spaces in items breaks up string

### ISSUE THREAD

**Issue by jaredtibs** [plemarquand/react-text-cycle#1]
Hi,

I'm encountering issues when I add a string with spaces to the  items prop.
e.g "Hello World"

That kind of string breaks up into pieces.

Is this a quick fix?

**Comment by plemarquand** [comment]
@jaredtibs Thanks for the report. Is it possible the container element is small enough that the string automatically wraps? You may want to add `white-space: nowrap;` to the container element to prevent this.

In the demo code one of the items has a space in it and it stays on the same line, which makes me think it might be that there isn't enough room in the container for all the text.

**Comment by jaredtibs** [comment]
@plemarquand yeah it was, in fact, a container issue. I set a fixed width and it ended up working nicely. Sry for the false alarm.

Thanks!

**Comment by plemarquand** [comment]
@jaredtibs No problem!
